name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_db" >> $GITHUB_ENV
        echo "DEBUG=${{ secrets.DEBUG }}" >> $GITHUB_ENV
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "AFRICAS_TALKING_USERNAME=${{ secrets.AFRICAS_TALKING_USERNAME }}" >> $GITHUB_ENV
        echo "AFRICAS_TALKING_API_KEY=${{ secrets.AFRICAS_TALKING_API_KEY }}" >> $GITHUB_ENV

    - name: Apply migrations
      run: |
          cd server
          python manage.py migrate

    - name: Run tests
      run: |
        cd server
        coverage run --source='.' manage.py test
        coverage report

    - name: Merge to main
      if: success()
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git fetch origin
        git checkout main
        git merge origin/development --no-ff --commit -m "Auto-merge from development to main"
        git push origin main
