name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd server
        coverage run --source='.' manage.py test
        coverage report

    - name: Merge to main
      if: success()
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git fetch origin
        git checkout main
        git merge origin/development --no-ff --commit -m "Auto-merge from development to main"
        git push origin main
